[project]
name = "ethereal-protocol-sync"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.synchronizer-ledger]
path = "contracts/synchronizer-ledger.clar"
depends_on = []

[contracts.access-authority]
path = "contracts/access-authority.clar"
depends_on = []

[contracts.integrity-verifier]
path = "contracts/integrity-verifier.clar"
depends_on = []

[contracts.version-tracker]
path = "contracts/version-tracker.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
